import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Info } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import WalletConnectDemo from '@/components/WalletConnectDemo';
import { useTranslation } from 'react-i18next';
export default function WalletDemo() {
    const { t } = useTranslation();
    return (_jsx("div", { className: "container mx-auto px-4 py-12", children: _jsxs("div", { className: "max-w-2xl mx-auto", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-4xl font-bold mb-4 gradient-text", children: t('walletDemo.title') }), _jsx("p", { className: "text-lg text-muted-foreground", children: t('walletDemo.subtitle') })] }), _jsx("div", { className: "mb-8", children: _jsx(WalletConnectDemo, {}) }), _jsxs(Card, { className: "glass-card border-primary/20", children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Info, { className: "h-5 w-5 text-primary" }), t('walletDemo.info.title')] }), _jsx(CardDescription, { children: t('walletDemo.info.subtitle') })] }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-2", children: t('walletDemo.features.title') }), _jsxs("ul", { className: "space-y-2 text-sm text-muted-foreground", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-1.5 w-1.5 rounded-full bg-primary" }), t('walletDemo.features.feature1')] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-1.5 w-1.5 rounded-full bg-secondary" }), t('walletDemo.features.feature2')] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-1.5 w-1.5 rounded-full bg-accent" }), t('walletDemo.features.feature3')] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-1.5 w-1.5 rounded-full bg-primary" }), t('walletDemo.features.feature4')] })] })] }), _jsx("div", { className: "p-4 bg-muted rounded-md", children: _jsxs("p", { className: "text-sm text-muted-foreground", children: [_jsx("strong", { className: "text-foreground", children: t('walletDemo.note.title') }), ' ', t('walletDemo.note.description')] }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-2", children: t('walletDemo.supported.title') }), _jsx("div", { className: "flex flex-wrap gap-2", children: ['Nami', 'Eternl', 'Yoroi', 'Flint', 'Gero', 'Typhon'].map((wallet) => (_jsx("div", { className: "px-3 py-1 bg-primary/10 text-primary text-sm rounded-full border border-primary/20", children: wallet }, wallet))) })] })] })] })] }) }));
}
